backend:
  name: git-gateway
  branch: main
media_folder: "static/img"
public_folder: "/img"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      # Core Content Fields
      - {
          label: "Title",
          name: "title",
          widget: "string",
          pattern: ["^.{30,65}$", "30-65 characters recommended for SEO"],
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "featured_image",
          widget: "image",
          media_library: { config: { multiple: false } },
          required: false,
        }

      # SEO Fields
      - label: "SEO Configuration"
        name: "seo"
        widget: "object"
        fields:
          - {
              label: "SEO Title",
              name: "title",
              widget: "string",
              required: false,
              hint: "60 characters max",
              pattern: ["^.{0,60}$", "Max 60 characters"],
            }
          - {
              label: "Meta Description",
              name: "description",
              widget: "text",
              required: false,
              hint: "155-160 characters ideal",
            }
          - {
              label: "Canonical URL",
              name: "canonical",
              widget: "string",
              required: false,
              hint: "For original content sources",
            }
          - {
              label: "Noindex",
              name: "noindex",
              widget: "boolean",
              default: false,
              required: false,
            }

      # Content Organization
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          default: ["hugo"],
          allow_add: true,
        }
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          default: ["web-development"],
          allow_add: true,
        }

      # Content Body
      - label: "Body"
        name: "body"
        widget: "markdown"
        hint: "Use <!--more--> to create summary excerpt"
        buttons:
          [
            "bold",
            "italic",
            "link",
            "heading-three",
            "quote",
            "code",
            "bulleted-list",
            "numbered-list",
          ]
        editor_components: ["image", "code-block"]

      # Optimized Excerpt
      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
        required: false
        hint: "Custom summary (override auto-generated from body)"
